using Aspire.Hosting;

var builder = DistributedApplication.CreateBuilder(args);

// Add PostgreSQL with pgAdmin for database management
var postgres = builder
    .AddPostgres("postgres")
    .WithPgAdmin();

var postgresDb = postgres.AddDatabase("quizymode");

// Add the API project using ProjectReference
// The Projects class is auto-generated by Aspire SDK from ProjectReferences
// This approach bypasses IDE launch issues that can occur with path-based AddProject
var api = builder.AddProject("quizymode-api", "../Quizymode.Api/Quizymode.Api.csproj")
    .WithReference(postgresDb)
    .WaitFor(postgresDb);

builder.Build().Run();
